python example.py --a=0 --b=0
python example.py --a=0 --b=1
python example.py --a=0 --b=2
python example.py --a=0 --b=3
python example.py --a=0 --b=4
python example.py --a=0 --b=5
python example.py --a=0 --b=6
python example.py --a=0 --b=7
python example.py --a=0 --b=8
python example.py --a=0 --b=9
python example.py --a=1 --b=0
python example.py --a=1 --b=1
python example.py --a=1 --b=2
python example.py --a=1 --b=3
python example.py --a=1 --b=4
python example.py --a=1 --b=5
python example.py --a=1 --b=6
python example.py --a=1 --b=7
python example.py --a=1 --b=8
python example.py --a=1 --b=9
python example.py --a=2 --b=0
python example.py --a=2 --b=1
python example.py --a=2 --b=2
python example.py --a=2 --b=3
python example.py --a=2 --b=4
python example.py --a=2 --b=5
python example.py --a=2 --b=6
python example.py --a=2 --b=7
python example.py --a=2 --b=8
python example.py --a=2 --b=9
python example.py --a=3 --b=0
python example.py --a=3 --b=1
python example.py --a=3 --b=2
python example.py --a=3 --b=3
python example.py --a=3 --b=4
python example.py --a=3 --b=5
python example.py --a=3 --b=6
python example.py --a=3 --b=7
python example.py --a=3 --b=8
python example.py --a=3 --b=9
python example.py --a=4 --b=0
python example.py --a=4 --b=1
python example.py --a=4 --b=2
python example.py --a=4 --b=3
python example.py --a=4 --b=4
python example.py --a=4 --b=5
python example.py --a=4 --b=6
python example.py --a=4 --b=7
python example.py --a=4 --b=8
python example.py --a=4 --b=9
python example.py --a=5 --b=0
python example.py --a=5 --b=1
python example.py --a=5 --b=2
python example.py --a=5 --b=3
python example.py --a=5 --b=4
python example.py --a=5 --b=5
python example.py --a=5 --b=6
python example.py --a=5 --b=7
python example.py --a=5 --b=8
python example.py --a=5 --b=9
python example.py --a=6 --b=0
python example.py --a=6 --b=1
python example.py --a=6 --b=2
python example.py --a=6 --b=3
python example.py --a=6 --b=4
python example.py --a=6 --b=5
python example.py --a=6 --b=6
python example.py --a=6 --b=7
python example.py --a=6 --b=8
python example.py --a=6 --b=9
python example.py --a=7 --b=0
python example.py --a=7 --b=1
python example.py --a=7 --b=2
python example.py --a=7 --b=3
python example.py --a=7 --b=4
python example.py --a=7 --b=5
python example.py --a=7 --b=6
python example.py --a=7 --b=7
python example.py --a=7 --b=8
python example.py --a=7 --b=9
python example.py --a=8 --b=0
python example.py --a=8 --b=1
python example.py --a=8 --b=2
python example.py --a=8 --b=3
python example.py --a=8 --b=4
python example.py --a=8 --b=5
python example.py --a=8 --b=6
python example.py --a=8 --b=7
python example.py --a=8 --b=8
python example.py --a=8 --b=9
python example.py --a=9 --b=0
python example.py --a=9 --b=1
python example.py --a=9 --b=2
python example.py --a=9 --b=3
python example.py --a=9 --b=4
python example.py --a=9 --b=5
python example.py --a=9 --b=6
python example.py --a=9 --b=7
python example.py --a=9 --b=8
python example.py --a=9 --b=9
